enum ValueType {
    price_field
    indicator
    constant
}

enum PriceField {
    close
    open
    high
    low
    volume
}

############### Query #####################
type IndicatorField {
    name: Indicator!
    params: IndicatorParams!
}

type Operand {
    type: ValueType!
    indicatorField: IndicatorField
    priceField: PriceField
    constantField: Float
    offset: Int
}

type Condition {
    left: Operand!
    operator: ComparisonOperator!
    right: Operand!
}

type LogicalGroup {
    operator: LogicalOperator!
    expressions: [Expression!]!
}

type Expression {
    condition: Condition
    logical: LogicalGroup
}

type SymbolRule {
    lookUpSymbol: String!
    instrument: Instrument!
    orderSymbol: String!
    expiry: String
    lotSize: Int!
}

type StrategyRule {
    symbols: [SymbolRule!]
    transaction: Transaction!
    profit: Float
    loss: Float
    entryLogic: Expression!
    exitLogic: Expression!
}

type Strategy {
    id: BsonId!
    name: String!
    userId: ID!
    startTime: String!
    endTime: String!
    createdAt: Time
    maxTransactionPerDay: Int
    maxProfit: Float
    maxLoss: Float
}
