package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	brokerlistentity "github.com/bharath0292/quantdrey/internal/domains/brokerlist/entity"
)

func (r *queryResolver) GetBrokers(ctx context.Context) ([]*brokerlistentity.Broker, error) {
	return r.brokerListService.GetBrokersList(ctx)
}
