package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"time"

	graph "github.com/bharath0292/quantdrey/graph/generated"
	strategydto "github.com/bharath0292/quantdrey/internal/domains/strategy/dto"
	strategyentity "github.com/bharath0292/quantdrey/internal/domains/strategy/entity"
)

// CreateStrategy is the resolver for the createStrategy field.
func (r *mutationResolver) CreateStrategy(ctx context.Context, input strategydto.NewStrategy) (*strategyentity.Strategy, error) {
	_ = r.strategyService.CreateStrategy(&input)

	now := time.Now()
	a := strategyentity.Strategy{
		Id:                   1,
		Name:                 input.Name,
		UserId:               input.UserId,
		StartTime:            input.StartTime,
		EndTime:              input.EndTime,
		Rule:                 input.Rule,
		CreatedAt:            &now,
		UpdatedAt:            &now,
		MaxTransactionPerDay: input.MaxTransactionPerDay,
		MaxProfit:            input.MaxProfit,
		MaxLoss:              input.MaxLoss,
	}

	return &a, nil
}

// ListAllStrategy is the resolver for the listAllStrategy field.
func (r *queryResolver) ListAllStrategy(ctx context.Context, userID string) (*strategyentity.Strategy, error) {
	panic(fmt.Errorf("not implemented: ListAllStrategy - listAllStrategy"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
